### ISSUE TITLE
add some showcase images/videos

### ISSUE THREAD

**Issue by justchokingaround** [sweetbbak/hyprland-dots#1]
do it now

<img width="120" alt="Screenshot 2023-08-13 at 23 37 13" src="https://github.com/sweetbbak/hyprland-dots/assets/44473782/c3aa14b6-c837-4cf8-87af-993c5906def1">

**Comment by sweetbbak** [comment]
lmaoo okay okay, just put the gun down

**Comment by justchokingaround** [comment]
![Screenshot_20230814_090216.jpg](https://github.com/sweetbbak/hyprland-dots/assets/44473782/0b27a866-d6ab-4f34-ab72-1388c0ee9eed)
